/**
 * Chat Messenger API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginInput { 
    /**
     * The username of the user
     */
    username: string;
    /**
     * The password of the user
     */
    password: string;
}

