openapi: 3.0.0
info:
  title: Chat Messenger API
  description: API documentation for Chat Messenger
  version: 1.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        "200":
          description: ""
components:
  schemas: {}
tags: []
servers: []
