openapi: 3.0.0
info:
  title: Chat Messenger API
  description: API documentation for Chat Messenger
  version: 1.0.0
paths:
  /auth/register:
    post:
      operationId: register
      summary: Register a new user
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterInput"
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Bad request, invalid input
      tags: &a1
        - Auth
  /auth/login:
    post:
      operationId: login
      summary: User login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginInput"
      responses:
        "201":
          description: Login successful
        "401":
          description: Unauthorized, invalid credentials
      tags: *a1
  /messages:
    post:
      operationId: send
      summary: Create a new message
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateMessageDto"
      responses:
        "201":
          description: Message created successfully
        "400":
          description: Invalid input data
        "500":
          description: Internal Server Error during message creation
      tags: &a2
        - Messages
      security: &a3
        - bearer: []
    get:
      operationId: findAll
      summary: Retrieve all messages for the user
      parameters:
        - name: timestamp
          required: true
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Messages retrieved successfully
        "403":
          description: Forbidden
        "500":
          description: "Internal Server Error during message retrieval "
      tags: *a2
      security: *a3
components:
  schemas:
    RegisterInput:
      type: object
      properties:
        username:
          type: string
          description: The username of the user
          example: johndoe
        password:
          type: string
          description: The password of the user. Must be at least 8 characters long.
          example: strongPassword123
          minLength: 6
      required:
        - username
        - password
    LoginInput:
      type: object
      properties:
        username:
          type: string
          example: johndoe
          description: The username of the user
        password:
          type: string
          example: strongPassword123
          description: The password of the user
      required:
        - username
        - password
    CreateMessageDto:
      type: object
      properties:
        content:
          type: string
          description: The message content
          example: Hi, can you help me?
      required:
        - content
tags: []
servers: []
